version: "2"
services:

  nginx:
    image: nginx
    restart: always
    env_file:
      - .env
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/usr/share/nginx/html
    ports:
      - "80:80"
    links:
      - php:php

  php:
    build: ./docker/php
    env_file:
      - .env
    restart: always
    expose:
      - "9000"
    links:
      - mysql
      - redis
    volumes:
      - ./:/usr/share/nginx/html
    command: sh -c "composer install"
  mysql:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis/data:/data
    command: redis-server --appendonly yes